# Generated by Django 3.1.12 on 2025-01-18 18:08

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('frames', djongo.models.fields.JSONField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
